CREATE DATABASE IF NOT EXISTS OurDatabase;
USE OurDatabase;

DROP TABLE IF EXISTS Transaction_Fees;
DROP TABLE IF EXISTS Transaction1;
DROP TABLE IF EXISTS UNREALIZED_GAIN_LOSS;
DROP TABLE IF EXISTS INVESTED_VALUE;
DROP TABLE IF EXISTS FUND_IN_PORTFOLIO;
DROP TABLE IF EXISTS BOND_IN_PORTFOLIO;
DROP TABLE IF EXISTS STOCK_IN_PORTFOLIO;
DROP TABLE IF EXISTS R_eturns;
DROP TABLE IF EXISTS Portfolio1;
DROP TABLE IF EXISTS FUND;
DROP TABLE IF EXISTS BOND;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS ASSET;
DROP TABLE IF EXISTS FINANCIAL_GOAL;
DROP TABLE IF EXISTS RISK_TOLERANCE;
DROP TABLE IF EXISTS INVESTOR;

-- Create INVESTOR Table
CREATE TABLE INVESTOR (
 Phone VARCHAR(15) PRIMARY KEY,
 Name VARCHAR(100) NOT NULL,
 Gender CHAR(1),
 DoB DATE,
 AnnualIncome DECIMAL(15, 2),
 Company VARCHAR(100)
);

-- Create RISK_TOLERANCE Table
CREATE TABLE RISK_TOLERANCE (
 Phone VARCHAR(15),
 RiskLevel VARCHAR(20),
 Q1A VARCHAR(255),
 Q2A VARCHAR(255),
 Q3A VARCHAR(255),
 Q4A VARCHAR(255),
 Q5A VARCHAR(255),
 PRIMARY KEY (Phone, RiskLevel),
 FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);

-- Create FINANCIAL_GOAL Table
CREATE TABLE FINANCIAL_GOAL (
 Goal VARCHAR(100),
 Phone VARCHAR(15),
 Amount DECIMAL(15, 2),
 Timeline INT,
 PRIMARY KEY (Goal, Phone),
 FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);

-- Create ASSET Table
CREATE TABLE ASSET (
 AssetID VARCHAR(20) PRIMARY KEY,
 Name VARCHAR(100),
 Price DECIMAL(15, 2)
);

-- Create STOCK Table
CREATE TABLE STOCK (
 AssetID VARCHAR(20) PRIMARY KEY,
 P_ERatio DECIMAL(10, 2),
 EPS DECIMAL(10, 2),
 EBITDA DECIMAL(15, 2),
 FOREIGN KEY (AssetID) REFERENCES ASSET(AssetID)
);

-- Create BOND Table
CREATE TABLE BOND (
 AssetID VARCHAR(20) PRIMARY KEY,
 InterestRate DECIMAL(5, 2),
 MaturityDate DATE,
 FOREIGN KEY (AssetID) REFERENCES ASSET(AssetID)
);

-- Create FUND Table
CREATE TABLE FUND (
 AssetID VARCHAR(20) PRIMARY KEY,
 ExpenseRatio DECIMAL(5, 2),
 DividendYield DECIMAL(5, 2),
 FOREIGN KEY (AssetID) REFERENCES ASSET(AssetID)
);

-- Create PORTFOLIO Table (Decomposed into Portfolio1 and PortfolioFeeStructure)
CREATE TABLE Portfolio1 (
 Phone VARCHAR(15),
 PID VARCHAR(20),
 MarketValue DECIMAL(15, 2),
 InceptionDate DATE,
 AnnualizedReturn DECIMAL(5, 2),
 PRIMARY KEY (PID, Phone), -- Composite primary key (order corrected)
 FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);





