USE OurDatabaseSCSBG1;

-- Reset
DROP TABLE IF EXISTS TRANSACTION_FEES;
DROP TABLE IF EXISTS TRANSACTION1;
DROP TABLE IF EXISTS UNREALIZED_GAIN_LOSS;
DROP TABLE IF EXISTS INVESTED_VALUE;
DROP TABLE IF EXISTS FUND_IN_PORTFOLIO;
DROP TABLE IF EXISTS BOND_IN_PORTFOLIO;
DROP TABLE IF EXISTS STOCK_IN_PORTFOLIO;
DROP TABLE IF EXISTS R3TURNS;
DROP TABLE IF EXISTS PORTFOLIO1;
DROP TABLE IF EXISTS FUND;
DROP TABLE IF EXISTS BOND;
DROP TABLE IF EXISTS STOCK;
DROP TABLE IF EXISTS ASSET;
DROP TABLE IF EXISTS FINANCIAL_GOAL;
DROP TABLE IF EXISTS RISK_TOLERANCE;
DROP TABLE IF EXISTS INVESTOR;

-- Create INVESTOR Table
CREATE TABLE INVESTOR (
    Phone VARCHAR(15) PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Gender CHAR(1),
    DoB DATE,
    AnnualIncome DECIMAL(15, 2),
    Company VARCHAR(100)
);

-- Create RISK_TOLERANCE Table
CREATE TABLE RISK_TOLERANCE (
    Phone VARCHAR(15),
    RiskLevel VARCHAR(20),
    Q1A VARCHAR(255),
    Q2A VARCHAR(255),
    Q3A VARCHAR(255),
    Q4A VARCHAR(255),
    Q5A VARCHAR(255),
    PRIMARY KEY (Phone, RiskLevel),
    FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);

-- Create FINANCIAL_GOAL Table
CREATE TABLE FINANCIAL_GOAL (
    Goal VARCHAR(100),
    Phone VARCHAR(15),
    Amount DECIMAL(15, 2),
    Timeline INT,
    PRIMARY KEY (Goal, Phone),
    FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);

-- Create ASSET Table
CREATE TABLE ASSET (
    AssetID VARCHAR(20) PRIMARY KEY,
    Name VARCHAR(100),
    Price DECIMAL(15, 2)
);

-- Create STOCK Table
CREATE TABLE STOCK (
    AssetID VARCHAR(20) PRIMARY KEY,
    P_ERatio DECIMAL(10, 2),
    EPS DECIMAL(10, 2),
    EBITDA DECIMAL(15, 2),
    FOREIGN KEY (AssetID) REFERENCES ASSET(AssetID)
);

-- Create BOND Table
CREATE TABLE BOND (
    AssetID VARCHAR(20) PRIMARY KEY,
    InterestRate DECIMAL(5, 2),
    MaturityDate DATE,
    FOREIGN KEY (AssetID) REFERENCES ASSET(AssetID)
);

-- Create FUND table
CREATE TABLE FUND (
    AssetID VARCHAR(20) PRIMARY KEY,
    ExpenseRatio DECIMAL(5, 2),
    DividendYield DECIMAL(5, 2),
    FOREIGN KEY (AssetID) REFERENCES ASSET(AssetID)
);

-- Create PORTFOLIO Table (Decomposed into PORTFOLIO1 and ReTURNS)
CREATE TABLE PORTFOLIO1 (
    Phone VARCHAR(15),
    PID VARCHAR(20),
    MarketValue DECIMAL(15, 2),
    InceptionDate DATE,
    Fee DECIMAL(15, 2),
    AnnualizedReturn DECIMAL(5, 2),
    PRIMARY KEY (PID, Phone),
    FOREIGN KEY (Phone) REFERENCES INVESTOR(Phone)
);

-- Create R3TURNS Table
CREATE TABLE R3TURNS (
    MarketValue DECIMAL(15, 2),
    InceptionDate DATE,
    AnnualizedReturn DECIMAL(5, 2),
    PRIMARY KEY (MarketValue, InceptionDate)
);

-- Create STOCK_IN_PORTFOLIO Table
CREATE TABLE STOCK_IN_PORTFOLIO (
    ID VARCHAR(20) PRIMARY KEY,
    PID VARCHAR(20),
    Phone VARCHAR(15),
    StartDate DATE,
    AllocationRatio DECIMAL(5, 2),
    PostTradeCO VARCHAR(100),
    AssetID VARCHAR(20),
    FOREIGN KEY (AssetID) REFERENCES STOCK(AssetID),
    FOREIGN KEY (PID, Phone) REFERENCES PORTFOLIO1(PID, Phone)
);

-- Create BOND_IN_PORTFOLIO Table
CREATE TABLE BOND_IN_PORTFOLIO (
    ID VARCHAR(20) PRIMARY KEY,
    PID VARCHAR(20),
    Phone VARCHAR(15),
    StartDate DATE,
    AllocationRatio DECIMAL(5, 2),
    PostTradeCO VARCHAR(100),
    AssetID VARCHAR(20),
    FOREIGN KEY (AssetID) REFERENCES BOND(AssetID),
    FOREIGN KEY (PID, Phone) REFERENCES PORTFOLIO1(PID, Phone)
);

-- Create FUND_IN_PORTFOLIO Table
CREATE TABLE FUND_IN_PORTFOLIO (
    ID VARCHAR(20) PRIMARY KEY,
    PID VARCHAR(20),
    Phone VARCHAR(15),
    StartDate DATE,
    AllocationRatio DECIMAL(5, 2),
    PostTradeCO VARCHAR(100),
    AssetID VARCHAR(20),
    FOREIGN KEY (AssetID) REFERENCES FUND(AssetID),
    FOREIGN KEY (PID, Phone) REFERENCES PORTFOLIO1(PID, Phone)
);

-- Create INVESTED_VALUE Table
CREATE TABLE INVESTED_VALUE (
    Phone VARCHAR(15),
    PID VARCHAR(20),
    Date DATE,
    Amount DECIMAL(15, 2),
    PRIMARY KEY (Phone, PID, Date),
    FOREIGN KEY (PID, Phone) REFERENCES PORTFOLIO1(PID, Phone)
);

-- Create UNREALIZED_GAIN_LOSS Table
CREATE TABLE UNREALIZED_GAIN_LOSS (
    Phone VARCHAR(15) NOT NULL,
    PID VARCHAR(20) NOT NULL,
    Date DATE NOT NULL,
    Amount DECIMAL(15, 2),
    PRIMARY KEY (Phone, PID, Date),
    FOREIGN KEY (PID, Phone) REFERENCES PORTFOLIO1(PID, Phone)
);

-- Create TRANSACTION Table (Decopmose into TRANSACTION1 and TRANSACTION_FEES)
CREATE TABLE TRANSACTION1 (
    ID VARCHAR(20),
    Date DATE,
    PID VARCHAR(20),
    Phone VARCHAR(15),
    Type VARCHAR(50),
    PRIMARY KEY (ID, Date),
    FOREIGN KEY (PID, Phone) REFERENCES PORTFOLIO1(PID, Phone)
);

-- Create TRANSACTION_FEES Table
CREATE TABLE TRANSACTION_FEES (
    Type VARCHAR(50) PRIMARY KEY,
    Fee DECIMAL(5, 2)
);
